package authz

func get(path string) string  { return "GET " + path }
func post(path string) string { return "POST " + path }
func put(path string) string  { return "PUT " + path }
func del(path string) string  { return "DELETE " + path }

var publicRoutes = []string{
	post("/auth/login"),
	get("/auth/google"),
	get("/auth/google/callback"),
	post("/auth/recovery-channels"),
	post("/auth/forgot-password"),
	post("/auth/verify-otp"),
	post("/auth/reset-password"),
	post("/auth/demo-register"),
	post("/auth/demo-register-google"),
	post("/auth/demo-resend"),
	post("/auth/demo-verify-otp"),
	post("/auth/verify-email"),

	get("/geocode"),
	get("/address-search"),
	get("/places-search"),

	get("/integrations/whatsapp/webhook"),
	post("/integrations/whatsapp/webhook"),
	post("/integrations/shopify/webhook"),
	post("/integrations/shopify/webhook/:integration_id"),
	post("/integrations/shopify/webhooks/compliance"),
	post("/integrations/shopify/webhooks/customers/data_request"),
	post("/integrations/shopify/webhooks/customers/redact"),
	post("/integrations/shopify/webhooks/shop/redact"),
	post("/integrations/transport/envioclick/webhook"),
	post("/integrations/transport/shipit/webhook"),
	put("/integrations/transport/shipit/webhook"),
	post("/meli/notification"),
	post("/meli/notifications"),
	post("/tiendanube/webhook"),
	post("/tiendanube/webhook/customers-data-request"),
	post("/tiendanube/webhook/customers-redact"),
	post("/tiendanube/webhook/store-redact"),
	post("/woocommerce/webhook"),
	post("/vtex/webhook"),
	post("/jumpseller/webhook"),
	post("/magento/webhook"),
	post("/exito/webhook"),
	post("/falabella/webhook"),
	post("/amazon/notification"),
	post("/siigo/webhook"),
	post("/webhooks/bold"),
	post("/webhooks/bold/test"),
	post("/webhooks/bancolombia"),
	post("/webhooks/bancolombia/test"),
	post("/webhooks/envioclick"),
	post("/webhooks/shipit"),
	put("/webhooks/shipit"),
	post("/monitoring/alerts/grafana"),

	get("/shopify/callback"),
	get("/meli/callback"),
	get("/tiendanube/callback"),
	get("/jumpseller/callback"),
	get("/integrations/shopify/oauth/token"),
	get("/integrations/meli/oauth/token"),
	get("/integrations/tiendanube/oauth/token"),
	get("/integrations/jumpseller/oauth/token"),
	get("/integrations/shopify/config"),
	post("/integrations/shopify/auth/login"),

	post("/shopify/shipping-rates/:integration_id"),
	post("/woocommerce/shipping-rates/:integration_id"),
	get("/woocommerce/dane/:integration_id/states"),
	get("/woocommerce/dane/:integration_id/cities"),
	post("/woocommerce/validate-address/:integration_id"),
	get("/woocommerce/checkout-config/:integration_id"),
	get("/woocommerce/plugin-download"),
	get("/woocommerce/carrier-logo/:carrier"),

	get("/public/tienda/:slug"),
	get("/public/tienda/:slug/catalog"),
	get("/public/tienda/:slug/categories"),
	get("/public/tienda/:slug/product/:id"),
	post("/public/tienda/:slug/contact"),
	post("/public/tienda/:slug/checkout/bold/signature"),
	get("/public/tienda/:slug/checkout/:reference/status"),
	post("/storefront/register"),
	get("/tracking/search"),
	get("/tracking/:tracking_number/history"),
	post("/public/marketing-leads"),
	post("/public/siigo-referrals"),
}

var authenticatedRoutes = []string{
	get("/auth/session"),
	get("/auth/verify"),
	get("/auth/roles-permissions"),
	get("/auth/me/access"),
	post("/auth/change-password"),
	post("/auth/generate-password"),

	get("/notify/sse/order-notify"),
	get("/notify/sse/order-notify/:businessID"),
	get("/ai/recommendation"),
	post("/ai/assistant/chat"),
	get("/ai/assistant/state"),
	post("/ai/assistant/intro-seen"),
	post("/ai/assistant/messages/:id/feedback"),
	post("/ai/assistant/messages/:id/click"),
	get("/ai/assistant/alerts"),
	get("/ai/assistant/alerts/unread"),
	post("/ai/assistant/alerts/seen"),

	get("/businesses/:id"),
	put("/businesses/:id"),
	get("/businesses/:id/fiscal-profile"),
	put("/businesses/:id/fiscal-profile"),
	get("/businesses/configured-resources"),
	get("/businesses/:id/configured-resources"),
	get("/businesses/simple"),

	get("/business-types"),
	get("/business-types/:id"),
	get("/resources"),
	get("/resources/:id"),
	get("/actions"),
	get("/actions/:id"),

	get("/order-statuses"),
	get("/order-statuses/:id"),
	get("/order-statuses/simple"),
	get("/order-status-mappings"),
	get("/order-status-mappings/:id"),
	get("/fulfillment-statuses"),
	get("/payment-statuses"),
	get("/channel-statuses"),
	get("/payments/channel-methods"),
	get("/payments/mappings"),
	get("/payments/mappings/:id"),
	get("/payments/mappings/integration/:type"),
	get("/payments/methods"),
	get("/payments/methods/:id"),
	get("/integration-categories"),
	get("/integration-types"),
	get("/integration-types/:id"),
	get("/integration-types/active"),
	get("/integration-types/code/:code"),
	get("/ecommerce-integration-types"),
	get("/notification-types"),
	get("/notification-types/:id"),
	get("/notification-event-types"),
	get("/notification-event-types/:id"),
	get("/integrations/simple"),

	get("/geozones"),
	get("/geozones/:id"),
	get("/geozones/display"),
	get("/geozones/lookup"),
	get("/geozones/order-zone"),
	get("/geozones/probability"),
	get("/geozones/probability-by-dane"),
	get("/geozones/probability/by-carrier"),

	get("/announcements/active"),
	get("/announcements/categories"),
	post("/announcements/:id/view"),

	get("/subscriptions/me"),
	get("/subscriptions/me/usage"),
	put("/subscriptions/me/auto-payment"),
	get("/subscriptions/my-modules"),
	get("/subscriptions/module-catalog"),
	get("/subscriptions/module-codes"),
	get("/subscriptions/types"),
	get("/subscriptions/types/:id"),
	post("/subscriptions/purchase"),
	post("/subscriptions/reactivate"),
	post("/subscriptions/overage/accept"),
	post("/subscriptions/overage/pay"),

	get("/public/tienda/:slug/session"),
	get("/public/tienda/:slug/addresses"),
	post("/public/tienda/:slug/addresses"),
	del("/public/tienda/:slug/addresses/:id"),
	put("/public/tienda/:slug/addresses/:id/primary"),
	get("/public/tienda/:slug/my-orders"),
	get("/public/tienda/:slug/my-prices"),
	put("/public/tienda/:slug/profile"),
	post("/public/tienda/:slug/profile/avatar"),

	get("/website-config"),
	put("/website-config"),
	get("/website-config/categories"),
	post("/website-config/image"),
	del("/website-config/image"),
}

var superAdminRoutes = []string{
	get("/businesses"),
	post("/businesses"),
	del("/businesses/:id"),
	put("/businesses/:id/activate"),
	put("/businesses/:id/deactivate"),
	put("/businesses/configured-resources/:resource_id/activate"),
	put("/businesses/configured-resources/:resource_id/deactivate"),

	post("/roles"),
	put("/roles/:id"),
	del("/roles/:id"),
	post("/roles/:id/permissions"),
	del("/roles/:id/permissions/:permission_id"),
	post("/permissions"),
	post("/permissions/bulk"),
	put("/permissions/:id"),
	del("/permissions/:id"),

	get("/integration-types/:id/platform-credentials"),
	get("/integration-types/code/:code/platform-credentials"),
	post("/integrations/sync-orders/business/:business_id"),

	get("/pay/wallet/all"),

	get("/subscriptions/admin/businesses"),
	get("/subscriptions/admin/kpis"),
	get("/subscriptions/audit-logs/:businessId"),
	get("/subscriptions/payments/:businessId"),
	post("/subscriptions/payments/:id/revert"),
	post("/subscriptions/register-payment"),
	post("/subscriptions/disable"),
	post("/subscriptions/extend-days"),
	put("/subscriptions/edit-dates"),
	post("/subscriptions/types"),
	put("/subscriptions/types/:id"),
	del("/subscriptions/types/:id"),

	post("/geozones"),
	post("/geozones/bulk"),
	del("/geozones/:id"),
	post("/geozones/display/flush-cache"),

	get("/marketing-leads"),
	get("/siigo-referrals"),
}

var permissionRoutes = map[string]RoutePolicy{
	post("/orders/:id/request-confirmation"):                           PermAction("orders", ActionUpdate),
	post("/orders/:id/send-guide-notification"):                        PermAction("orders", ActionUpdate),
	post("/orders-compare/apply"):                                      PermAction("orders", ActionUpdate),
	post("/pay/wallet/debit-guide"):                                    PermAction("shipments", ActionCreate),
	get("/integrations/meli/shipments/:shipment_id/label"):             PermAction("shipments", ActionRead),
	get("/siigo/invoices/:invoiceID/pdf"):                              PermAction("invoicing", ActionRead),
	post("/users/:id/assign-role"):                                     PermAction("users", ActionUpdate),
	post("/customers/upload-bulk"):                                     PermAction("customers", ActionCreate),
	get("/integrations"):                                               AnyPermission("integrations.read", "orders.read"),
	get("/integrations/stats"):                                         AnyPermission("integrations.read", "orders.read"),
	post("/integrations/whatsapp/send-template"):                       Perm("notifications"),
	post("/integrations/whatsapp/conversations/:id/reply"):             Perm("notifications"),
	post("/integrations/whatsapp/conversations/:id/reply-media"):       Perm("notifications"),
	post("/integrations/whatsapp/conversations/:id/pause-ai"):          PermAction("notifications", ActionUpdate),
	post("/integrations/whatsapp/conversations/:id/resume-ai"):         PermAction("notifications", ActionUpdate),
	post("/notification-configs/message-audit/conversations/:id/read"): PermAction("notifications", ActionRead),
}

var prefixRules = []PrefixRule{
	{Prefix: "/orders", Policy: Perm("orders")},
	{Prefix: "/orders-compare", Policy: Perm("orders")},
	{Prefix: "/mobile/orders", Policy: Perm("orders")},
	{Prefix: "/products", Policy: Perm("products")},
	{Prefix: "/customers", Policy: Perm("customers")},
	{Prefix: "/pricing", Policy: Perm("customers")},
	{Prefix: "/shipments", Policy: Perm("shipments")},
	{Prefix: "/cod-report", Policy: Perm("shipments")},
	{Prefix: "/shipping-config", Policy: Perm("shipments")},
	{Prefix: "/invoicing", Policy: Perm("invoicing")},
	{Prefix: "/inventory", Policy: Perm("inventory")},
	{Prefix: "/warehouses", Policy: Perm("warehouses")},
	{Prefix: "/zones", Policy: Perm("warehouses")},
	{Prefix: "/aisles", Policy: Perm("warehouses")},
	{Prefix: "/racks", Policy: Perm("warehouses")},
	{Prefix: "/rack-levels", Policy: Perm("warehouses")},
	{Prefix: "/pay", Policy: Perm("wallet")},
	{Prefix: "/pay/wallet/admin", Policy: SuperAdmin()},
	{Prefix: "/users", Policy: Perm("users")},
	{Prefix: "/roles", Policy: Perm("roles")},
	{Prefix: "/permissions", Policy: Perm("permissions")},
	{Prefix: "/integrations", Policy: Perm("integrations")},
	{Prefix: "/meli", Policy: Perm("integrations")},
	{Prefix: "/tiendanube", Policy: Perm("integrations")},
	{Prefix: "/woocommerce", Policy: Perm("integrations")},
	{Prefix: "/vtex", Policy: Perm("integrations")},
	{Prefix: "/jumpseller", Policy: Perm("integrations")},
	{Prefix: "/siigo", Policy: Perm("integrations")},
	{Prefix: "/tiktok", Policy: Perm("integrations")},
	{Prefix: "/notification-configs", Policy: Perm("notifications")},
	{Prefix: "/scheduled-notification-rules", Policy: Perm("notifications")},
	{Prefix: "/whatsapp-templates", Policy: Perm("notifications")},
	{Prefix: "/whatsapp-flows", Policy: Perm("notifications")},
	{Prefix: "/whatsapp-campaigns", Policy: Perm("notifications")},
	{Prefix: "/notification-backfill", Policy: Perm("notifications")},
	{Prefix: "/routes", Policy: Perm("delivery")},
	{Prefix: "/drivers", Policy: Perm("delivery")},
	{Prefix: "/vehicles", Policy: Perm("delivery")},
	{Prefix: "/storefront", Policy: Perm("storefront")},

	{Prefix: "/dashboard", Policy: Authenticated()},
	{Prefix: "/legal", Policy: Authenticated()},
	{Prefix: "/tours", Policy: Authenticated()},
	{Prefix: "/push", Policy: Authenticated()},

	{Prefix: "/ai/assistant/admin", Policy: SuperAdmin()},
	{Prefix: "/accounting", Policy: SuperAdmin()},
	{Prefix: "/announcements", Policy: SuperAdmin()},
	{Prefix: "/commercial", Policy: SuperAdmin()},
	{Prefix: "/tickets", Policy: SuperAdmin()},
	{Prefix: "/sprints", Policy: SuperAdmin()},
	{Prefix: "/shipping-margins", Policy: SuperAdmin()},
	{Prefix: "/woo-store", Policy: SuperAdmin()},
	{Prefix: "/subscriptions", Policy: SuperAdmin()},
	{Prefix: "/business-types", Policy: SuperAdmin()},
	{Prefix: "/resources", Policy: SuperAdmin()},
	{Prefix: "/actions", Policy: SuperAdmin()},
	{Prefix: "/order-statuses", Policy: SuperAdmin()},
	{Prefix: "/order-status-mappings", Policy: SuperAdmin()},
	{Prefix: "/channel-statuses", Policy: SuperAdmin()},
	{Prefix: "/payments", Policy: SuperAdmin()},
	{Prefix: "/integration-types", Policy: SuperAdmin()},
	{Prefix: "/notification-types", Policy: SuperAdmin()},
	{Prefix: "/notification-event-types", Policy: SuperAdmin()},
}

func buildExact() map[string]RoutePolicy {
	exact := make(map[string]RoutePolicy, len(publicRoutes)+len(authenticatedRoutes)+len(superAdminRoutes)+len(permissionRoutes))
	for _, r := range publicRoutes {
		exact[r] = Public()
	}
	for _, r := range authenticatedRoutes {
		exact[r] = Authenticated()
	}
	for _, r := range superAdminRoutes {
		exact[r] = SuperAdmin()
	}
	for r, p := range permissionRoutes {
		exact[r] = p
	}
	return exact
}

var RoutePolicies = NewPolicyTable(buildExact(), prefixRules)
