import type { TourDefinition } from '../domain/types';

export const homeTour: TourDefinition = {
    key: 'home',
    version: 1,
    title: 'Recorrido general',
    routes: ['/home'],
    autoStart: true,
    steps: [
        {
            id: 'welcome',
            title: 'Bienvenido a Probability',
            body: 'Este recorrido te muestra para que sirve cada módulo del menú lateral. Toma un minuto.\n\nPuedes cerrarlo con la X y retomarlo cuando quieras desde el botón de ayuda.',
        },
        {
            id: 'orders',
            title: 'Ordenes',
            body: 'El corazón de la operación. Aquí llegan los pedidos de todos tus canales (Shopify, MercadoLibre, WooCommerce, WhatsApp) y desde aquí generas las guías de envío.',
            target: 'a[href="/orders"]',
            placement: 'right',
            optional: true,
        },
        {
            id: 'inventory',
            title: 'Inventario',
            body: 'Catalogo de productos, bodegas, stock, movimientos y kardex. El stock que ves en una orden sale de aquí.',
            target: 'a[href^="/inventory"], a[href="/products"]',
            placement: 'right',
            optional: true,
        },
        {
            id: 'wallet',
            title: 'Billetera',
            body: 'Tu saldo para pagar guías. Cada envío descuenta de aquí, así que si el saldo llega a cero no se pueden generar más guías.',
            target: 'a[href="/wallet"]',
            placement: 'right',
            optional: true,
        },
        {
            id: 'integrations',
            title: 'Integraciones',
            body: 'Conecta tus canales de venta y transportadoras. Sin una integración configurada, los pedidos de ese canal no entran solos.',
            target: 'a[href="/integrations"]',
            placement: 'right',
            optional: true,
        },
        {
            id: 'customers',
            title: 'Clientes',
            body: 'La base de clientes que se arma sola con las órdenes: historial de compras, direcciones y datos de contacto.',
            target: 'a[href="/customers"]',
            placement: 'right',
            optional: true,
        },
        {
            id: 'delivery',
            title: 'Domicilios',
            body: 'Flota propia: rutas, conductores, vehículos y geozonas. Para lo que entregas tu mismo en vez de mandarlo por transportadora.',
            target: 'a[href="/delivery/routes"]',
            placement: 'right',
            optional: true,
        },
        {
            id: 'invoicing',
            title: 'Facturacion',
            body: 'Facturas electrónicas hacia la DIAN a través de tu proveedor (Siigo, Factus). Se alimenta de las órdenes.',
            target: 'a[href="/invoicing/invoices"]',
            placement: 'right',
            optional: true,
        },
        {
            id: 'notifications',
            title: 'Notificaciones',
            body: 'Que se le avisa al cliente y por donde: WhatsApp o correo, en cada cambio de estado de su pedido.',
            target: 'a[href="/notification-config"]',
            placement: 'right',
            optional: true,
        },
        {
            id: 'website',
            title: 'Mi sitio web',
            body: 'Tu tienda publica y su configuración: catalogo, colores, dominio y contenido.',
            target: 'a[href="/website-config"]',
            placement: 'right',
            optional: true,
        },
        {
            id: 'tickets',
            title: 'Soporte',
            body: 'Tickets de soporte. Si algo falla en la operación, se reporta aquí y queda con historial.',
            target: 'a[href="/tickets"]',
            placement: 'right',
            optional: true,
        },
        {
            id: 'end',
            title: 'Listo',
            body: 'Cada módulo tiene su propio tutorial. Entra a cualquiera y se abre solo la primera vez, o presiona el botón de ayuda abajo a la derecha.\n\nPuedes reiniciarlos todos desde tu perfil.',
        },
    ],
};
