import type { TourDefinition } from '../domain/types';

export const homeTour: TourDefinition = {
    key: 'home',
    version: 1,
    title: 'Recorrido general',
    routes: ['/home'],
    autoStart: true,
    steps: [
        {
            id: 'welcome',
            title: 'Bienvenido a Probability',
            body: 'Este recorrido te muestra para que sirve cada modulo del menu lateral. Toma un minuto.\n\nPuedes cerrarlo con la X y retomarlo cuando quieras desde el boton de ayuda.',
        },
        {
            id: 'orders',
            title: 'Ordenes',
            body: 'El corazon de la operacion. Aqui llegan los pedidos de todos tus canales (Shopify, MercadoLibre, WooCommerce, WhatsApp) y desde aqui generas las guias de envio.',
            target: 'a[href="/orders"]',
            placement: 'right',
            optional: true,
        },
        {
            id: 'inventory',
            title: 'Inventario',
            body: 'Catalogo de productos, bodegas, stock, movimientos y kardex. El stock que ves en una orden sale de aqui.',
            target: 'a[href^="/inventory"], a[href="/products"]',
            placement: 'right',
            optional: true,
        },
        {
            id: 'wallet',
            title: 'Billetera',
            body: 'Tu saldo para pagar guias. Cada envio descuenta de aqui, asi que si el saldo llega a cero no se pueden generar mas guias.',
            target: 'a[href="/wallet"]',
            placement: 'right',
            optional: true,
        },
        {
            id: 'integrations',
            title: 'Integraciones',
            body: 'Conecta tus canales de venta y transportadoras. Sin una integracion configurada, los pedidos de ese canal no entran solos.',
            target: 'a[href="/integrations"]',
            placement: 'right',
            optional: true,
        },
        {
            id: 'customers',
            title: 'Clientes',
            body: 'La base de clientes que se arma sola con las ordenes: historial de compras, direcciones y datos de contacto.',
            target: 'a[href="/customers"]',
            placement: 'right',
            optional: true,
        },
        {
            id: 'delivery',
            title: 'Domicilios',
            body: 'Flota propia: rutas, conductores, vehiculos y geozonas. Para lo que entregas tu mismo en vez de mandarlo por transportadora.',
            target: 'a[href="/delivery/routes"]',
            placement: 'right',
            optional: true,
        },
        {
            id: 'invoicing',
            title: 'Facturacion',
            body: 'Facturas electronicas hacia la DIAN a traves de tu proveedor (Siigo, Factus). Se alimenta de las ordenes.',
            target: 'a[href="/invoicing/invoices"]',
            placement: 'right',
            optional: true,
        },
        {
            id: 'notifications',
            title: 'Notificaciones',
            body: 'Que se le avisa al cliente y por donde: WhatsApp o correo, en cada cambio de estado de su pedido.',
            target: 'a[href="/notification-config"]',
            placement: 'right',
            optional: true,
        },
        {
            id: 'website',
            title: 'Mi sitio web',
            body: 'Tu tienda publica y su configuracion: catalogo, colores, dominio y contenido.',
            target: 'a[href="/website-config"]',
            placement: 'right',
            optional: true,
        },
        {
            id: 'tickets',
            title: 'Soporte',
            body: 'Tickets de soporte. Si algo falla en la operacion, se reporta aqui y queda con historial.',
            target: 'a[href="/tickets"]',
            placement: 'right',
            optional: true,
        },
        {
            id: 'end',
            title: 'Listo',
            body: 'Cada modulo tiene su propio tutorial. Entra a cualquiera y se abre solo la primera vez, o presiona el boton de ayuda abajo a la derecha.\n\nPuedes reiniciarlos todos desde tu perfil.',
        },
    ],
};
