package errors

import "errors"

var (
	ErrProductNotFound        = errors.New("producto no encontrado")
	ErrWarehouseNotFound      = errors.New("bodega no encontrada")
	ErrInsufficientStock      = errors.New("stock insuficiente para esta operacion")
	ErrInvalidQuantity        = errors.New("la cantidad no puede ser cero")
	ErrSameWarehouse          = errors.New("la bodega de origen y destino deben ser diferentes")
	ErrTransferQtyNeg         = errors.New("la cantidad a transferir debe ser positiva")
	ErrProductNoTracking      = errors.New("el producto no tiene seguimiento de inventario habilitado")
	ErrMovementTypeNotFound   = errors.New("tipo de movimiento no encontrado")
	ErrMovementTypeCodeExists = errors.New("el codigo del tipo de movimiento ya existe")
	ErrNoDefaultWarehouse     = errors.New("no se encontro bodega por defecto para el negocio")

	ErrLotNotFound         = errors.New("lote no encontrado")
	ErrDuplicateLotCode    = errors.New("el codigo de lote ya existe para este producto")
	ErrLotExpired          = errors.New("el lote esta vencido")
	ErrSerialNotFound      = errors.New("numero de serie no encontrado")
	ErrSerialNotAvailable  = errors.New("numero de serie no disponible")
	ErrDuplicateSerial     = errors.New("el numero de serie ya existe para este producto")
	ErrUomNotFound         = errors.New("unidad de medida no encontrada")
	ErrUomConversion       = errors.New("error en conversion de unidad de medida")
	ErrStateNotFound       = errors.New("estado de inventario no encontrado")
	ErrStateTransition     = errors.New("transicion de estado no permitida")
	ErrProductUoMNotFound  = errors.New("unidad de medida del producto no encontrada")

	ErrPutawayRuleNotFound       = errors.New("regla de put-away no encontrada")
	ErrPutawaySuggestionNotFound = errors.New("sugerencia de put-away no encontrada")
	ErrPutawayAlreadyConfirmed   = errors.New("sugerencia de put-away ya fue confirmada")
	ErrReplenishmentNotFound     = errors.New("tarea de reabastecimiento no encontrada")
	ErrReplenishmentClosed       = errors.New("tarea de reabastecimiento ya cerrada")
	ErrCrossDockNotFound         = errors.New("enlace cross-dock no encontrado")
	ErrCrossDockExecuted         = errors.New("enlace cross-dock ya ejecutado")
	ErrNoPutawayRule             = errors.New("no se encontro regla de put-away aplicable")

	ErrCountPlanNotFound   = errors.New("plan de conteo ciclico no encontrado")
	ErrCountTaskNotFound   = errors.New("tarea de conteo ciclico no encontrada")
	ErrCountTaskClosed     = errors.New("tarea de conteo ciclico ya cerrada")
	ErrCountLineNotFound   = errors.New("linea de conteo ciclico no encontrada")
	ErrCountLineSubmitted  = errors.New("linea de conteo ciclico ya enviada")
	ErrDiscrepancyNotFound = errors.New("discrepancia no encontrada")
	ErrDiscrepancyResolved = errors.New("discrepancia ya resuelta")

	ErrLPNNotFound       = errors.New("LPN no encontrada")
	ErrDuplicateLPNCode  = errors.New("el codigo de LPN ya existe")
	ErrLPNDissolved      = errors.New("LPN ya disuelta")
	ErrLPNEmpty          = errors.New("LPN vacia")
	ErrScanNotResolved   = errors.New("el codigo escaneado no corresponde a ninguna entidad")
	ErrDuplicateSyncHash = errors.New("payload ya procesado (idempotencia)")
)
